version: '3.8'

services:
  ollama-base:
    image: ollama/ollama
    container_name: ollama_server_base
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          cpus: '4.0'   # Minimum 4 CPUs
          memory: 8g    # Minimum 8 GB of RAM
    environment:
      - SOME_ENV_VAR=value
    volumes:
      - ollama:/root/.ollama

  ollama-nvidia:
    extends: ollama-base
    container_name: ollama_server_nvidia
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    profiles:
      - nvidia

  ollama-amd:
    extends: ollama-base
    container_name: ollama_server_amd
    image: ollama/ollama:rocm
    devices:
      - /dev/kfd
      - /dev/dri
    profiles:
      - amd

volumes:
  ollama:
